import type { Metadata } from 'next';
import './globals.css';
import Panel from '@/components/panel';
import Dock from '@/components/Dock';
import { WindowProvider } from '@/components/WindowContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="font-sf  bg-[url('/bg.jpg')] bg-cover antialiased">
        <WindowProvider>
          <div className="relative h-screen w-screen overflow-hidden">
            <Panel />
            <main className="absolute inset-0 z-0">{children}</main>
            <Dock />
          </div>
        </WindowProvider>
      </body>
    </html>
  );
}
