
export const apps = [
  {
    id: 'launchpad',
    appName: 'LaunchPad',

    icon: '/launchpad.png',
    maximizeable: false,
    componentName: 'apps/Launchpad',
    additionalData: {},
    multiwindow: false,
    titlebarblurred: false,
    pinned: true,
  },
  {
    id: 'finder',
    appName: 'Finder',
    icon: '/finder.png',
    maximizeable: true,
    componentName: 'apps/Finder',
    additionalData: {},
    multiwindow: true,
    titlebarblurred: true,
    pinned: true,
  },
  {
    id: 'settings',
    appName: 'Settings',
    icon: '/settings.png',
    maximizeable: true,
    componentName: 'apps/Settings',
    additionalData: {},
    multiwindow: true,
    titlebarblurred: true,
    pinned: true,
  },

  {
    id: 'python',
    appName: 'Python IDE',
    icon: '/code.png',
    maximizeable: true,
    componentName: 'apps/Python',
    additionalData: {},
    multiwindow: true,
    titlebarblurred: false,
    pinned: true,
  },
  {
    id: 'mail',
    appName: 'Mail',
    icon: '/mail.png',
    maximizeable: true,
    componentName: 'Mail',
    additionalData: {},
    multiwindow: true,
    titlebarblurred: false,
    pinned: true,
  },
  {
    id: 'calendar',
    appName: 'Calendar',
    icon: '/calendar.png',
    maximizeable: true,
    componentName: 'apps/Calendar',
    additionalData: {},
    multiwindow: true,
    titlebarblurred: false,
    pinned: true,
  },
  {
    id: 'calculator',
    appName: 'Calculator',
    icon: '/calculator.png',
    maximizeable: true,
    componentName: 'Calculator',
    additionalData: {},
    multiwindow: false,
    titlebarblurred: false,
    pinned: true,
  },
  {
    id: 'appstore',
    appName: 'App Store',
    icon: '/appstore.png',
    maximizeable: false,
    componentName: 'AppStore',
    additionalData: {},
    multiwindow: false,
    titlebarblurred: false,
    pinned: true,
  },
  {
    id: 'safari',
    appName: 'Safari',
    icon: '/safari.png',
    maximizeable: true,
    componentName: 'apps/Safari',
    additionalData: {},
    multiwindow: true,
    titlebarblurred: true,
    pinned: true,
  },
  {
    id: 'welcome',
    appName: 'Welcome',
    icon: '/info.png',
    maximizeable: false,
    componentName: 'Welcome',
    additionalData: {},
    multiwindow: false,
    titlebarblurred: false,
    pinned: false,
  }


];
