
  export const apps = [
    {
      id: 'launchpad',
      appName: 'LaunchPad',
      
      icon: 'launchpad.png',
      maximizeable: false,
      componentName: 'AppStore',
      additionalData: {},
      multiwindow: false,
      titlebarblurred: false,
      pinned: true,
    },
    {
      id: 'finder',
      appName: 'Finder',
      icon: '/finder.png',
      maximizeable: true,
      componentName: 'Finder',
      additionalData: {},
      multiwindow: true,
      titlebarblurred: true,
      pinned: true,
    },
    {
      id: 'settings',
      appName: 'Settings',
      icon: '/settings.png',
      maximizeable: true,
      componentName: 'Settings',
      additionalData: {},
      multiwindow: true,
      titlebarblurred: true,
      pinned: true,
    },
    {
      id: 'xcode',
      appName: 'XCode',
      icon: '/code.png',
      maximizeable: true,
      componentName: 'BalaDev',
  additionalData: {startLarge: true},
      multiwindow: true,
      titlebarblurred: true,
      pinned: true,
    },
    {
      id: 'mail',
      appName: 'Mail',
      icon: '/mail.png',
      maximizeable: true,
      componentName: 'Mail',
      additionalData: {},
      multiwindow: true,
      titlebarblurred: false,
      pinned: true,
    },
    {
      id: 'calendar',
      appName: 'Calendar',
      icon: 'calendar.png',
      maximizeable: true,
      componentName: 'Calendar',
      additionalData: {},
      multiwindow: true,
      titlebarblurred: false,
      pinned: true,
    },
    {
      id: 'calculator',
      appName: 'Calculator',
      icon: 'calculator.png',
      maximizeable: true,
      componentName: 'Calculator',
      additionalData: {},
      multiwindow: false,
      titlebarblurred: false,
      pinned: true,
    },
    {
      id: 'appstore',
      appName: 'App Store',
      
      icon: 'appstore.png',
      maximizeable: false,
      componentName: 'AppStore',
      additionalData: {},
      multiwindow: false,
      titlebarblurred: false,
      pinned: false,
    },
    {
      id: 'welcome',
      appName: 'Welcome',
      icon: 'info.png',
      maximizeable: false,
      componentName: 'Welcome',
      additionalData: {},
      multiwindow: false,
      titlebarblurred: false,
      pinned:false,
    }


  ];
